name: LIN3 - Matrix2 Pipeline

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true 
      matrix:
        python-version: [3.8,3.9, 3.11, 3.58] #3.58 is not a valid version, it will fail due to fail-fast: true

    steps:
      - uses: actions/checkout@v4

      - name: Show version
        run: echo "Running on Python ${{ matrix.python-version }}"
 

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
         python-version: ${{ matrix.python-version }}