name: LIN15.0-ECR-ECS deploy
on:
 workflow_dispatch:
 push:
  branches:
    - main

permissions:
  id-token: write
  contents: read
  security-events: write
  actions: read

env:
    AWS_REGION: ${{ secrets.AWS_REGION }}
    AWS_REPOSITORY: ${{ secrets.AWS_REPOSITORY }}
    IMAGE_TAG: "v-${{ github.sha }}"
    AWS_ROLE_ARN_MAIN: ${{ secrets.AWS_ROLE_ARN_MAIN }}

jobs:
    awsCreds-connection:
        name: AWS Credentials & SVC Connection
        runs-on: ubuntu-latest

        outputs:
          aws-ecr-login: ${{ steps.login-ecr.outputs.registry }}
          image_uri: ${{ steps.set-image-uri.outputs.image_uri }}

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              role-to-assume: ${{ secrets.AWS_ROLE_ARN_MAIN }}
              aws-region: ${{ env.AWS_REGION }}
    
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v2
            with:
              mask-password: false

          - name: Echo ECR login success
            run: |
                echo "Logged in to Amazon ECR successfully"

          - name: Set ECR_REGISTRY environment variable
            env:
              ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            run: echo "ECR_REGISTRY=${ECR_REGISTRY}" >> $GITHUB_ENV

          - name: Generate Short SHA  
            run: |
                SHORT_SHA="v-${GITHUB_SHA::7}"
                FULL_IMAGE_URI="${ECR_REGISTRY}/$AWS_REPOSITORY:${SHORT_SHA}"

                docker build -t $FULL_IMAGE_URI .
                docker tag $FULL_IMAGE_URI $ECR_REGISTRY/$AWS_REPOSITORY:latest

                echo "Docker image built and tagged successfully"

                docker push $FULL_IMAGE_URI
                docker push $ECR_REGISTRY/$AWS_REPOSITORY:latest

                echo "Pushed Docker image to ECR successfully"

          - name: Full URI of the pushed image
            id: set-image-uri
            run: |
                echo "image_uri=${ECR_REGISTRY}/${{ env.AWS_REPOSITORY }}:$SHORT_SHA" >> $GITHUB_OUTPUT

    deploy-to-ecs:
        name: Deploy to Amazon ECS
        needs: awsCreds-connection
        runs-on: ubuntu-latest

        env:
          IMAGE_URI: ${{ needs.awsCreds-connection.outputs.image_uri }}

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              role-to-assume: ${{ secrets.AWS_ROLE_ARN_MAIN }}
              aws-region: ${{ env.AWS_REGION }}

          - name: Get current task definition
            run: |
                aws ecs describe-task-definition \
                  --task-definition lin15-td \
                   --query 'taskDefinition' > current_td.json

                echo "Current task definition retrieved successfully"

          - name: Update task definition with new image
            run: |
                jq --arg IMAGE "$IMAGE_URI" \
                   --arg NAME "lin15-td" \
                   '.containerDefinitions | map(if .name == $NAME then .image = $IMAGE else . end) \
                   | del(
                   .taskDefinitionArn,
                   .revision,
                   .status,
                   .requiresAttributes,
                   .compatibilities,
                   .registeredAt,
                   .deregisteredAt,
                   .registeredBy
                   )' current_td.json > new_td.json

                echo "Task definition updated with new image successfully"

          - name: Register new task definition
            run: |
                NEW_TDF_REG=$(aws ecs register-task-definition \
                  --cli-input-json file://new_td.json \
                  --query 'taskDefinition.taskDefinitionArn' \
                  --output text)
                echo "New task definition registered successfully"

          - name: Update ECS service to use new task definition
            run: |
                aws ecs update-service \
                  --cluster lin15-cluster \
                  --service lin15-service \
                  --task-definition $NEW_TDF_REG
                  --force-new-deployment

                echo "ECS service updated to use new task definition successfully"

          - name: ECS Service Deployment Status
            run: |
                aws ecs wait services-stable \
                  --cluster lin15-cluster \
                  --services lin15-service