name: LIN15.0-ECR-ECS deploy
on:
 workflow_dispatch:
 push:
  branches:
    - main

permissions:
  contents: read
  security-events: write
  actions: read

env:
    AWS_REGION: ap-south-1
    AWS_REPOSITORY: hellobuddy

jobs:
    awsCreds-connection:
        name: AWS Credentials & SVC Connection
        runs-on: ubuntu-latest
        outputs:
          aws-ecr-login: ${{ steps.login-ecr.outputs.registry }}

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v3
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_MAIN }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_MAIN }}
              aws-region: ${{ env.AWS_REGION }}

          - name: Echo success message
            run: |
                echo "AWS credentials configured successfully"
    
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v2
            with:
              mask-password: false

          - name: Echo ECR login success
            run: |
                echo "Logged in to Amazon ECR successfully"
                echo "ECR Registry: ${{ steps.login-ecr.outputs.registry }}"

          - name: Set ECR_REGISTRY environment variable
            run: |
                echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

          - name: Generate Short SHA  
            run: |
                SHORT_SHA="v-${ GITHUB_SHA::7 }"
                echo "Short SHA: $SHORT_SHA" >> $GITHUB_ENV

          - name: Build Docker Image
            run: |
                docker build -t ${{ env.AWS_REPOSITORY }}:$SHORT_SHA .
                docker tag ${{ env.AWS_REPOSITORY }}:$SHORT_SHA $ECR_REGISTRY/${{ env.AWS_REPOSITORY }}:latest

                echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
                echo "Docker image built and tagged successfully"

          - name: Push Docker Image to ECR
            run: |
                docker push $ECR_REGISTRY/${{ env.AWS_REPOSITORY }}:$SHORT_SHA
                docker push $ECR_REGISTRY/${{ env.AWS_REPOSITORY }}:latest

                echo "Pushed Docker image to ECR successfully"

