name: LIN15.0-ECR-ECS deploy
on:
 workflow_dispatch:
 push:
  branches:
    - main

permissions:
  contents: read
  security-events: write
  actions: read

env:
    AWS_REGION: ap-south-1

jobs:
    awsCreds-connection:
        name: AWS Credentials & SVC Connection
        runs-on: ubuntu-latest
        outputs:
          aws-ecr-login: ${{ steps.login-ecr.outputs.aws-ecr-login }}

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v3
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_MAIN }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_MAIN }}
              aws-region: ${{ env.AWS_REGION }}

          - name: Echo success message
            run: |
                echo "AWS credentials configured successfully"
    
    ecr-login:
        runs-on: ubuntu-latest
        
        steps:
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v2
            with:
              mask-password: false

          - name: Echo ECR login success
            run: |
                echo "Logged in to Amazon ECR successfully"

