name: LIN3 - Matrix Pipeline

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: [ww, 3.10, 3.11]

    steps:
      - uses: actions/checkout@v4

      - name: Show version
        run: echo "Running on Python ${{ matrix.python-version }}"