name: LIN-10 List S3 Buckets
on:
    workflow_dispatch:
        

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs: 
  s3-buckets-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Connect to AWS
        uses: ./.github/actions/simple-action.yml
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: List Buckets
        shell: bash
        run: aws s3 ls