name: LIN4-2 - Artifacts Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create artifact
        run: |
            mkdir -p artifactsdir
            echo "This is an artifact" > artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: artifactsdirnm-build
          path: artifactsdir/artifact.txt


  download:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download artifact
        # actions/download-artifact@v4 will create the artifactsdir and download the artifact.txt into it
          uses: actions/download-artifact@v5
          with:
            name: artifactsdirnm-build
            path: artifactsdir
          
        - name: Show artifact content
          run: cat artifactsdir/artifact.txt


        # - name: withoutDownload artifact || Show artifact content
        #   run: cat artifactsdir/artifact.txt
