name: LIN3 - Matrix Pipeline

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, 3.11, 4.0]

    steps:
      - uses: actions/checkout@v4

      - name: Show version
        run: echo "Running on Python ${{ matrix.python-version }}"
 

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
         python-version: ${{ matrix.python-version }}