name: LIN11 - Docker Build & Push

on:
 workflow_dispatch:

concurrency:
  group: "ga-lin-sl-11-${{ github.ref }}" 
  cancel-in-progress: true           # if "TRUE" - it cancels all currently running jobs in the same group, if "FALSE" - it allows all jobs to run

permissions:
    id-token: write
    contents: read

env:
  ECR= ${{ secrets.AWS_ORG_ID}}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

jobs:
  pre-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Simple Echo Step
        run: |
         echo "Performing Action - AWS oidc pre-checks"
          echo "Checking AWS CLI Version"

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: pre-checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Verify identity
        run: aws sts get-caller-identity


      - name: S1. Login to ECR
        run: |
         aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS \
          --password-stdin ${{ env.ECR }}

      - name: S2. Build Docker image
        run: |
         docker build -t py_app:${{ github.sha }} .

      - name: S3. Tagging and Pushing
        run: |
         set -e

         docker tag py_app:${{ github.sha }} ${{ env.ECR }}/py_app:${{ github.sha }}
         docker tag py_app:${{ github.sha }} ${{ env.ECR }}/py_app:latest

         docker push ${{ env.ECR }}/py_app:${{ github.sha }}
         docker push ${{ env.ECR }}/py_app:latest
