name: LIN9 - Re-UseIT

on:
 workflow_call:
   inputs:
     node-version:
       description: 'Node.js version to use'
       required: true
       default: '20'
       type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - run: npm test