name: LIN14.1 - Trivy DevSecOps Security Scan

on:
    workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
   security-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln,secret
          severity: HIGH,CRITICAL,LOW,MEDIUM
          exit-code: 1
          format: table

#image build
      - name: Build Docker Image
        run: |
          docker build -t py-app:${{ github.sha }} .

#image scan
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          scan-ref: py-app:${{ github.sha }}
          scanners: vuln,secret
          severity: HIGH,CRITICAL,LOW,MEDIUM
          exit-code: 1
          format: table      

      - name: Generate Trivy SARIF Report
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: py-app:${{ github.sha }}
          format: sarif
          output: trivy-results.sarif
      # ==========================================================
      # Upload SARIF Report
      # ==========================================================
      - name: Upload Trivy SARIF Report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results.sarif
      # ==========================================================
      - name: SARIF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sarif-report
          path: trivy-results.sarif