name: LIN14.1 - Trivy DevSecOps Security Scan

on:
    workflow_dispatch:

jobs:
   security-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln,misconfig,secret
          severity: HIGH,CRITICAL,LOW,MEDIUM
          exit-code: 1
          format: table