name: LIN9.2 - Call Re-Usable yamls

on:
  workflow_dispatch:

jobs:
  call-build:
    uses: ./.github/workflows/ga-lin-sl-09_rw-builder-01.yml   #.github/workflows/ga-lin-sl-09_rw-builder-01.yml refers to the reusable workflow file
    with:
      node-version: '24'