name: LIN6.1 - Outputs

on:
  workflow_dispatch:
env:
  EXAMPLE_ENV_VAR: "This is an example environment variable"
  AWS_ORG_ID: ${{ secrets.AWS_ORG_ID }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
jobs:
  tests:
    runs-on: ubuntu-latest

    outputs:
      eg_op1: ${{ steps.set_output.outputs.eg_op }}
      eg_step_op1: ${{ steps.set_output.outputs.eg_step_op }}

    steps:
      - name: Set output
        id: set_output
        env:
          ENV_VAR_IN_STEP1: "This is an example output variable"
        

        run: |
         echo "eg_op=$EXAMPLE_ENV_VAR" >> $GITHUB_OUTPUT
         echo "ENV_VAR_IN_STEP1=$ENV_VAR_IN_STEP1" >> $GITHUB_ENV
         echo "eg_step_op=$ENV_VAR_IN_STEP1" >> $GITHUB_OUTPUT
        

      - name: Use output
        run: |
          echo "The output from the previous step is: ${{ steps.set_output.outputs.eg_op }}"
          echo "The step output is: ${{ steps.set_output.outputs.eg_step_op }}"

      - name: Pulling info from env&secrets var
        run: |
          echo "Pulling info from secret var: ${{ secrets.AWS_ORG_ID}}"
          echo "Pulling info from env var: ${{ env.AWS_ORG_ID}}"
  test2:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Use output from previous job
        run: |
          echo "The output from the previous job is: ${{ needs.tests.outputs.eg_op1 }}"