name: LIN13 - Git Leak Detection

on: [push, pull_request, workflow_dispatch]

jobs:
  git-leak-detection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v2
