name: Deploy to EKS

on:
  workflow_dispatch:

# Ensure only one deploy runs at a time to prevent state conflicts
concurrency:
  group: eks-deploy-${{ github.ref }}
  cancel-in-progress: false 

permissions:
  id-token: write
  contents: read

env:
  ECR_REGISTRY: ${{ secrets.AWS_ORG_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
  REPO_NAME: py_app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: |
        
          aws eks update-kubeconfig \
            --name sravan-eks-c02 \
            --region ${{ vars.AWS_REGION }}

      - name: Run Test POD
        run: |
          kubectl cluster-info

          # Use apply -f for directory or specific files to ensure idempotency and proper management of Kubernetes resources
          kubectl run test-pod --image=busybox \
            --restart=Never \
            -- sleep 3600 \
            --dry-run=client -o yaml > k8s/basepod0.yaml
      
      - name: pullPods
        run: |
            kubectl apply -f k8s/basepod0.yaml

      - name: Wait for Test POD to be Running
        run: |
            kubectl get pods test-pod -o jsonpath='{.status.phase}' | grep -q "Running" || exit 1
            kubectl get pods test-pod -o wide
            
