name: Deploy to EKS (Helm)

on:
  workflow_dispatch:

concurrency:
  group: eks-deploy-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

env:
  ECR_REGISTRY: ${{ secrets.AWS_ORG_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
  REPO_NAME: py_app
  CLUSTER_NAME: sravan-eks-c02

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name $CLUSTER_NAME \
            --region ${{ vars.AWS_REGION }}

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Deploy with Helm
        run: |
          helm upgrade --install dep-base ./py-app \
            --set image.repository=${{ env.ECR_REGISTRY }}/${{ env.REPO_NAME }} \
            --set image.tag=${{ env.TAG }} \
            --atomic --wait --timeout 120s

      - name: Show Helm release
        run: |
          helm status dep-base